### ISSUE TITLE
提个建议，能否不要过度封装？

### ISSUE THREAD

**Issue by a1067111756** [jinmao88/vben3#15]
1. vben2就属于过度封装，组件自我造轮子，内部组件交叉引用，对框架进行改造难度很大。 
2. vben2太多地方造轮子，导致过于冗杂了，开发环境进入首页加载四百多个请求耗时几十秒的体验实在太差
3. vben3是否能考虑下不要过度封装，把框架的部分和提供使用者部分隔离分开

**Comment by jinmao88** [comment]
vben3有仓库 你可以了解一下

**Comment by jinmao88** [comment]
已经减少深度封装了
