### ISSUE TITLE
VbenForm组件应该与useForm解耦

### ISSUE THREAD

**Issue by tky753** [jinmao88/vben3#17]
VbenForm组件单独用的时候(`<vben-form :rule="{...}">`)， `rules` 参数无效
因为对rules 特殊处理了，只有用useForm的时候才能正确传入

**Comment by jinmao88** [comment]
贴一下代码

**Comment by tky753** [comment]
@jinmao88 
```vue
<script setup lang="ts">
  import { FormRules } from 'naive-ui'
  import { ref } from 'vue'

  const formData = ref({})
  const rules: FormRules = {
    name: {
      required: true
    }
  }
</script>
<template>
  <h1>Test</h1>
  <vben-form v-model:model="formData" :rules="rules">
    <vben-form-item label="名" path="name">
      <vben-input  v-model:value="formData.name"/>
    </vben-form-item>
  </vben-form>
</template>
```
实际上
![image](https://user-images.githubusercontent.com/18205977/196307823-d5efed71-6265-4add-92d7-de3dd9c7cc2f.png)

本应该
![image](https://user-images.githubusercontent.com/18205977/196307908-3bcee9d4-e03c-4417-9731-69da4893e505.png)

**Comment by jinmao88** [comment]
改好了
