### ISSUE TITLE
如何实现表格多列字段排序，然后把排序发送给后端

### ISSUE THREAD

**Issue by qq23230233** [jinmao88/vben3#24]
目前表格，使用 sorter: true,开启表格排序。同一时刻仅能排序一个列字段。

`
  {
    title: '用户名称',
    dataIndex: 'name',
    sorter: true,
    width: 400,
  },
 {
    title: '部门名称',
    dataIndex: 'orgName',
    sorter: true,
    width: 400,
  },
`

**Comment by jinmao88** [comment]
![image](https://user-images.githubusercontent.com/50581550/203281060-133b3828-82ea-4a74-bf5e-f3fcd79fae86.png)
